import './globals.css'
import "./styles/Pagenation.scss"
import "./styles/layout.scss"
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TagProvider } from "./context/TagContext"
import Header from "./components/Header/Header.jsx"
import Footer from "./components/Footer/Footer.jsx"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TagProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </TagProvider>
      </body>
    </html>
  )
}
